error_on_line_overflow = true
error_on_unformatted = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
imports_granularity = "Crate"
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
wrap_comments = true
